// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of CnetNEWS_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class CnetNEWS_DetailViewModel : ViewModelsBase.VMBase, IViewModels.ICnetNEWS_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.CnetNEWS_s4 _cnetNEWS_s4;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="CnetNEWS_DetailViewModel" /> class.
        /// </summary>
        /// <param name="cnetNEWS_s4">The Cnet N E W S_s4.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public CnetNEWS_DetailViewModel(Repositories.CnetNEWS_s4 cnetNEWS_s4, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_cnetNEWS_s4 = cnetNEWS_s4;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaCnetNEWS_Detail0;

        /// <summary>
        /// HasNextpanoramaCnetNEWS_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaCnetNEWS_Detail0
        {
            get
            {
				return _hasNextpanoramaCnetNEWS_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaCnetNEWS_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaCnetNEWS_Detail0;

        /// <summary>
        /// HasPreviouspanoramaCnetNEWS_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaCnetNEWS_Detail0
        {
            get
            {
				return _hasPreviouspanoramaCnetNEWS_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaCnetNEWS_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechCnetNEWS_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechCnetNEWS_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechCnetNEWS_DetailStaticControlCommand
        {
            get { return _textToSpeechCnetNEWS_DetailStaticControlCommand = _textToSpeechCnetNEWS_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechCnetNEWS_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareCnetNEWS_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareCnetNEWS_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareCnetNEWS_DetailStaticControlCommand
        {
            get { return _shareCnetNEWS_DetailStaticControlCommand = _shareCnetNEWS_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareCnetNEWS_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartCnetNEWS_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.ICnetNEWS_DetailViewModel), CreateTileInfoCnetNEWS_DetailStaticControl());
        }
		

        private ICommand _pinToStartCnetNEWS_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartCnetNEWS_DetailStaticControlCommand
        {
            get { return _pinToStartCnetNEWS_DetailStaticControlCommand = _pinToStartCnetNEWS_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartCnetNEWS_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceCnetNEWS_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceCnetNEWS_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceCnetNEWS_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceCnetNEWS_DetailStaticControlCommand
        {
            get { return _goToSourceCnetNEWS_DetailStaticControlCommand = _goToSourceCnetNEWS_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceCnetNEWS_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaCnetNEWS_Detail0 command.
        /// </summary>
        public async void NextpanoramaCnetNEWS_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _cnetNEWS_s4.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaCnetNEWS_Detail0;

        /// <summary>
        /// Gets the NextpanoramaCnetNEWS_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaCnetNEWS_Detail0
        {
            get { return _nextpanoramaCnetNEWS_Detail0 = _nextpanoramaCnetNEWS_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaCnetNEWS_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaCnetNEWS_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaCnetNEWS_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _cnetNEWS_s4.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaCnetNEWS_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaCnetNEWS_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaCnetNEWS_Detail0
        {
            get { return _previouspanoramaCnetNEWS_Detail0 = _previouspanoramaCnetNEWS_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaCnetNEWS_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaCnetNEWS_Detail0 = await _cnetNEWS_s4.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaCnetNEWS_Detail0 = await _cnetNEWS_s4.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the CnetNEWS_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoCnetNEWS_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "DoWApp-Logo.png"
            };
            return tileInfo;
        }
    }
}
