// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of NDTVGadgets_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class NDTVGadgets_DetailViewModel : ViewModelsBase.VMBase, IViewModels.INDTVGadgets_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.NDTVGadgets_s1 _nDTVGadgets_s1;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="NDTVGadgets_DetailViewModel" /> class.
        /// </summary>
        /// <param name="nDTVGadgets_s1">The N D T V Gadgets_s1.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public NDTVGadgets_DetailViewModel(Repositories.NDTVGadgets_s1 nDTVGadgets_s1, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_nDTVGadgets_s1 = nDTVGadgets_s1;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaNDTVGadgets_Detail0;

        /// <summary>
        /// HasNextpanoramaNDTVGadgets_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaNDTVGadgets_Detail0
        {
            get
            {
				return _hasNextpanoramaNDTVGadgets_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaNDTVGadgets_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaNDTVGadgets_Detail0;

        /// <summary>
        /// HasPreviouspanoramaNDTVGadgets_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaNDTVGadgets_Detail0
        {
            get
            {
				return _hasPreviouspanoramaNDTVGadgets_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaNDTVGadgets_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechNDTVGadgets_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechNDTVGadgets_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechNDTVGadgets_DetailStaticControlCommand
        {
            get { return _textToSpeechNDTVGadgets_DetailStaticControlCommand = _textToSpeechNDTVGadgets_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechNDTVGadgets_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareNDTVGadgets_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareNDTVGadgets_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareNDTVGadgets_DetailStaticControlCommand
        {
            get { return _shareNDTVGadgets_DetailStaticControlCommand = _shareNDTVGadgets_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareNDTVGadgets_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartNDTVGadgets_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.INDTVGadgets_DetailViewModel), CreateTileInfoNDTVGadgets_DetailStaticControl());
        }
		

        private ICommand _pinToStartNDTVGadgets_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartNDTVGadgets_DetailStaticControlCommand
        {
            get { return _pinToStartNDTVGadgets_DetailStaticControlCommand = _pinToStartNDTVGadgets_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartNDTVGadgets_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceNDTVGadgets_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceNDTVGadgets_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceNDTVGadgets_DetailStaticControlCommand
        {
            get { return _goToSourceNDTVGadgets_DetailStaticControlCommand = _goToSourceNDTVGadgets_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceNDTVGadgets_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaNDTVGadgets_Detail0 command.
        /// </summary>
        public async void NextpanoramaNDTVGadgets_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _nDTVGadgets_s1.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaNDTVGadgets_Detail0;

        /// <summary>
        /// Gets the NextpanoramaNDTVGadgets_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaNDTVGadgets_Detail0
        {
            get { return _nextpanoramaNDTVGadgets_Detail0 = _nextpanoramaNDTVGadgets_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaNDTVGadgets_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaNDTVGadgets_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaNDTVGadgets_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _nDTVGadgets_s1.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaNDTVGadgets_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaNDTVGadgets_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaNDTVGadgets_Detail0
        {
            get { return _previouspanoramaNDTVGadgets_Detail0 = _previouspanoramaNDTVGadgets_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaNDTVGadgets_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaNDTVGadgets_Detail0 = await _nDTVGadgets_s1.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaNDTVGadgets_Detail0 = await _nDTVGadgets_s1.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the NDTVGadgets_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoNDTVGadgets_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "DoWApp-Logo.png"
            };
            return tileInfo;
        }
    }
}
