// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// CNET_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ICNET_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaCNET_Detail0 property.
        /// </summary>
		bool HasNextpanoramaCNET_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaCNET_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaCNET_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechCNET_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechCNET_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareCNET_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareCNET_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartCNET_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartCNET_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceCNET_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceCNET_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaCNET_Detail0 command.
        /// </summary>
		ICommand NextpanoramaCNET_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaCNET_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaCNET_Detail0 { get; }

	}
}
