// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// GeekyGadgets_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IGeekyGadgets_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaGeekyGadgets_Detail0 property.
        /// </summary>
		bool HasNextpanoramaGeekyGadgets_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaGeekyGadgets_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaGeekyGadgets_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechGeekyGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechGeekyGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareGeekyGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareGeekyGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartGeekyGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartGeekyGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceGeekyGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceGeekyGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaGeekyGadgets_Detail0 command.
        /// </summary>
		ICommand NextpanoramaGeekyGadgets_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaGeekyGadgets_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaGeekyGadgets_Detail0 { get; }

	}
}
