// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// NDTVGadgets_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface INDTVGadgets_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaNDTVGadgets_Detail0 property.
        /// </summary>
		bool HasNextpanoramaNDTVGadgets_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaNDTVGadgets_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaNDTVGadgets_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechNDTVGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareNDTVGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartNDTVGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceNDTVGadgets_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceNDTVGadgets_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaNDTVGadgets_Detail0 command.
        /// </summary>
		ICommand NextpanoramaNDTVGadgets_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaNDTVGadgets_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaNDTVGadgets_Detail0 { get; }

	}
}
