// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Videos_DetailVideos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IVideos_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		EntitiesBase.YouTubeVideo CurrentYouTubeVideo { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaVideos_DetailVideos0 property.
        /// </summary>
		bool HasNextpanoramaVideos_DetailVideos0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaVideos_DetailVideos0 property.
        /// </summary>
		bool HasPreviouspanoramaVideos_DetailVideos0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechVideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechVideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareVideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand ShareVideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartVideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartVideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceVideos_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceVideos_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaVideos_DetailVideos0 command.
        /// </summary>
		ICommand NextpanoramaVideos_DetailVideos0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaVideos_DetailVideos0 command.
        /// </summary>
		ICommand PreviouspanoramaVideos_DetailVideos0 { get; }

	}
}
