// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	UnityContainer.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc = WPAppStudio.Ioc.Interfaces;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Microsoft.Practices.Unity;
using Repositories = WPAppStudio.Repositories;
using RepositoriesBase = WPAppStudio.Repositories.Base;
using Services = WPAppStudio.Services;
using ViewModels = WPAppStudio.ViewModel;

namespace WPAppStudio.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Container : IIoc.IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public Container()
        {
            _currentContainer = new UnityContainer();

            _currentContainer.RegisterType<IServices.ILiveTileService, Services.LiveTileService>();
			_currentContainer.RegisterType<IServices.ILockScreenService, Services.LockScreenService>();
			_currentContainer.RegisterType<IServices.IProximityService, Services.ProximityService>();
            _currentContainer.RegisterType<IServices.IDialogService, Services.DialogService>();
            _currentContainer.RegisterType<IServices.IShareService, Services.ShareService>();
			
            _currentContainer.RegisterType<IServices.ISpeechService, Services.SpeechService>();
            _currentContainer.RegisterType<IServices.INavigationService, Services.NavigationService>();
			
		
		    _currentContainer.RegisterType<IServices.IStorageService, Services.StorageService>();
			_currentContainer.RegisterType<IServices.IInternetService, Services.InternetService>(new ContainerControlledLifetimeManager());
			_currentContainer.RegisterType<RepositoriesBase.IXmlDataSource, RepositoriesBase.XmlDataSource>();
			_currentContainer.RegisterType<RepositoriesBase.IYoutubeDataSource, RepositoriesBase.YoutubeDataSource>();
            _currentContainer.RegisterType<IViewModels.INDTVGadgets_NewsViewModel, ViewModels.NDTVGadgets_NewsViewModel>();
            _currentContainer.RegisterType<IViewModels.IVideos_DetailVideosViewModel, ViewModels.Videos_DetailVideosViewModel>();
            _currentContainer.RegisterType<IViewModels.ICnetNEWS_DetailViewModel, ViewModels.CnetNEWS_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IGeekyGadgets_DetailViewModel, ViewModels.GeekyGadgets_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.ICNET_DetailViewModel, ViewModels.CNET_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.INDTVGadgets_DetailViewModel, ViewModels.NDTVGadgets_DetailViewModel>();

			_currentContainer.RegisterType<IViewModels.IAboutViewModel, ViewModels.AboutViewModel>(new ContainerControlledLifetimeManager());
			_currentContainer.RegisterType<IViewModels.ILicenseViewModel, ViewModels.LicenseViewModel>(new ContainerControlledLifetimeManager());
			
			if (!System.ComponentModel.DesignerProperties.IsInDesignTool)
            {
				_currentContainer.RegisterType<Repositories.INDTVGadgets_s1, Repositories.NDTVGadgets_s1>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ICNET_s2, Repositories.CNET_s2>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IGeekyGadgets_s3, Repositories.GeekyGadgets_s3>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ICnetNEWS_s4, Repositories.CnetNEWS_s4>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IVideos_s5, Repositories.Videos_s5>(new ContainerControlledLifetimeManager());
			}
			else
			{
				_currentContainer.RegisterType<Repositories.INDTVGadgets_s1, Repositories.FakeNDTVGadgets_s1>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ICNET_s2, Repositories.FakeCNET_s2>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IGeekyGadgets_s3, Repositories.FakeGeekyGadgets_s3>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ICnetNEWS_s4, Repositories.FakeCnetNEWS_s4>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IVideos_s5, Repositories.FakeVideos_s5>(new ContainerControlledLifetimeManager());
			
			}
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
